### PR TITLE
updated favicon

### PR DESCRIPTION
**Pull request by spdev7**

### CODE REVIEW

**Comment by spdev7** [comment]
Changing the favicon to Mail my ballot logo

**Comment by tianhuil** [comment]
Thanks.  Could you upload the 32x32 Favico?  This would be great to have.

**Comment by spdev7** [comment]
Sure,will update it soon.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by spdev7** [comment]
Updated the favicon with a 32x32 version

**Comment by tianhuil** [comment]
Thanks @spdev7: we'll take a look.

**Pull request closed without merging**
