### PR TITLE
Loading Indicators

### PR DESCRIPTION
**Pull request by ludanin**
- [x] Replaces cursor with a loading indicator when fetching data;
- [x] No longer trigger unnecessary toasts on `Base.tx`;
- [x] No longer trigger unnecessary toasts on `AddressForm.tx`;
- [x] No longer trigger unnecessary toasts on `Blurb.tx`;
- [x] Create a similar effect for mobile devices;
- [x] See why tests are failing and fix them;
- [x] Decide whether to use the overlay globally (then remove the device detection algorithm);
- [x] See if we should use this effect when compressing images;

If I'm missing any Component or place where these indicators would be useful, please let me know.

Cheers!

https://lu-mmb.ludanin.vercel.app

### CODE REVIEW

**Comment by marcoacfilho** [comment]
Looks good @ludanin but I could barely see the loading indicator close to my mouse. @tianhuil wouldn't it be better to have like a loading overlay ?

**Comment by ludanin** [comment]
@marcoacfilho Hey thanks for the feedback! I'm about to push some changes to this, since mobile devices don't even have cursors. On mobile devices an overlay is shown, but if needed we can make that the default even on desktop devices.

**Comment by ludanin** [comment]
Hey I did some changes, now it shows an overlay on top of the entire content on mobile devices.

On this Vercel instance: https://lu-mmb-81u9vyro7.vercel.app the effect also happens on desktop devices (so we can decide which approach to use), I really think it is better to use the same effect on both (the main link https://lu-mmb.ludanin.vercel.app still only shows the effect on mobile).

Again, thanks for the input, if you have any other suggestions feel free to share!

Cheers!

**Comment by tianhuil** [comment]
Try rerunning the test by making tiny whitespace tweaks.

**Comment by tianhuil** [comment]
I like https://lu-mmb-81u9vyro7.vercel.app (I think it works well both in desktop and mobile).  I guess we don't need to detect for mobile.  See if the designers have any easily implementable feedback.  Otherwise, I think it's pretty good.

**Pull request merged**
