### PR TITLE
Responsive design

### PR DESCRIPTION
**Pull request by marcoacfilho**
image

image

image

image

### CODE REVIEW

**Comment by marcoacfilho** [comment]
This is just the beginning but at least we have a platform that works on mobile as well, before it was really broken.

**Comment by marcoacfilho** [comment]
Here is the link: https://mail-my-ballot-mqk6blikm.now.sh/#/org/default

**Comment by tianhuil** [comment]
Thanks!  This is great and using custom `<P> <H1>` makes a lot of sense.  A few thoughts:
- We use left align (not center) for CSS.  Could you fix that on Mobile?
- Your buttons on mobile seem bigger than on the desktop.  Could you fix that?
- Could you make sure this works for iphone5/SE?  Currently, it's not great (you can see this in the Chrome render):

image

**Comment by marcoacfilho** [comment]
The buttons are bigger on purpose for accessibility purposes. But I can make them a bit smaller for sure

Marco Carvalho
+55 19 99927-5827
+1 917 266-0461

On Fri, 29 May 2020 at 21:30 Michael Li <Michael Li <mailto:Michael%20Li%20<notifications@github.com>> > wrote:

Thanks! This is great and using custom <P> <H1> makes a lot of sense. A few thoughts:

  *   We use left align (not center) for CSS. Could you fix that on Mobile?
  *   Your buttons on mobile seem bigger than on the desktop. Could you fix that?
  *   Could you make sure this works for iphone5/SE? Currently, it's not great (you can see this in the Chrome render):

[image]<https://user-images.githubusercontent.com/1906321/83314970-e9bdfa80-a1d1-11ea-9a7c-10d330cbf418.png>

**Comment by iraycd** [comment]
@tianhuil Do you have any style guideline and resource?

**Comment by tianhuil** [comment]
> @tianhuil Do you have any style guideline and resource?

Unfortunately nothing detailed.  But you can just match the desktop edition.

**Pull request closed without merging**
